#lang racket/base
;; Textual LLVM IR emission. Contracts arrive verified; this is transcription:
;;   @noalias -> noalias, @effect -> readonly/writeonly, @vectorize -> !llvm.loop,
;;   @fp(reassoc) -> reassoc flags. Locals are allocas; mem2reg rebuilds SSA.
(require racket/match racket/string racket/format racket/flonum
         "ast.rkt" "sema.rkt" "transform.rkt")
(provide emit-module)

(define (llty t)
  (match t
    ['void "void"] ['float "float"] ['usize "i64"] ['bool "i1"]
    [(Ptr _ _) "ptr"]))

;; LLVM spells `float` constants as the bit pattern of the f64 that the f32
;; value widens to.
(define (flit x)
  (define s (flsingle (exact->inexact x)))
  (define bs (real->floating-point-bytes s 8 #t))
  (define n (integer-bytes->integer bs #f #t))
  (format "0x~a" (string-upcase (~r n #:base 16 #:min-width 16 #:pad-string "0"))))

;; the loop metadata a kernel's contracts ask for, as rendered node bodies
(define (loop-md-entries c)
  (define v (Contracts-vectorize c))
  (define u (Contracts-unroll c))
  (append
   (cond
     [(and v (Vectorize-disable? v))
      (list "!{!\"llvm.loop.vectorize.enable\", i1 false}")]
     [v
      (append
       (list "!{!\"llvm.loop.vectorize.enable\", i1 true}")
       (let ([w (Vectorize-width v)])
         (if w (list (format "!{!\"llvm.loop.vectorize.width\", i32 ~a}" w)) '()))
       (let ([il (Vectorize-interleave v)])
         (if il (list (format "!{!\"llvm.loop.interleave.count\", i32 ~a}" il)) '()))
       (if (Vectorize-predicate? v)
           (list "!{!\"llvm.loop.vectorize.predicate.enable\", i1 true}")
           '())
       (if (Vectorize-scalable? v)
           (list "!{!\"llvm.loop.vectorize.scalable.enable\", i1 true}")
           '()))]
     [else '()])
   (if u
       (list (format "!{!\"llvm.loop.unroll.count\", i32 ~a}" (Unroll-count u)))
       '())))

(define (emit-module source-name kernels)
  (define md '())     ; list of (id . entries)
  (define md-next 0)
  (define (md-alloc! entries)
    (define id md-next)
    (set! md-next (+ md-next 1 (length entries)))
    (set! md (append md (list (cons id entries))))
    id)
  (define o (open-output-string))
  (fprintf o "; generated by wyvec 0.1 (Wyve stage 0, Racket)\nsource_filename = \"~a\"\n" source-name)
  (for ([k (in-list kernels)])
    (fprintf o "\n")
    (emit-kernel o k md-alloc!))
  (fprintf o "\nattributes #0 = { nounwind }\n")
  (unless (null? md)
    (fprintf o "\n")
    (for ([entry (in-list md)])
      (define id (car entry))
      (define bodies (cdr entry))
      (fprintf o "!~a = distinct !{~a}\n" id
               (string-join (for/list ([i (in-range (add1 (length bodies)))])
                              (format "!~a" (+ id i)))
                            ", "))
      (for ([b (in-list bodies)] [i (in-naturals 1)])
        (fprintf o "!~a = ~a\n" (+ id i) b))))
  (get-output-string o))

(define (emit-kernel o k md-alloc!)
  (define decl (kernel-decl k))
  (define eff (Contracts-effect (Sig-contracts decl)))
  (define param-strs
    (for/list ([p (in-list (sig-params decl))])
      (define attrs
        (if (Ptr? (Param-ty p))
            (let* ([r (if eff
                          (and (member (Param-name p) (Effect-reads eff)) #t)
                          (Ptr-const? (Param-ty p)))]
                   [w (if eff
                          (and (member (Param-name p) (Effect-writes eff)) #t)
                          #f)])
              (string-append
               (if (Param-noalias? p) " noalias" "")
               " nocapture"
               (cond [(and r (not w)) " readonly"]
                     [(and w (not r)) " writeonly"]
                     [else ""])))
            ""))
      (format "~a~a %~a" (llty (Param-ty p)) attrs (Param-name p))))
  (fprintf o "; kernel ~a [~a]\ndefine ~a @~a(~a) #0 {\n"
           (kernel-iface k) (sig-selector decl) (llty (Sig-ret decl)) (kernel-symbol k)
           (string-join param-strs ", "))

  ;; scheduling transforms run here, above LLVM, on the proven AST
  (define body
    (let ([ti (Contracts-tile (Sig-contracts decl))]
          [b (MethodDef-body (kernel-def k))])
      (if ti (apply-tile b (Tile-pairs ti)) b)))

  (define tmp 0)
  (define loopn 0)
  (define (t!) (begin0 (format "%t~a" tmp) (set! tmp (add1 tmp))))
  (define locals (make-hash))   ; name -> ty (alloca at %name.addr)
  (define params (for/hash ([p (in-list (sig-params decl))]) (values (Param-name p) (Param-ty p))))
  (define reassoc? (Contracts-fp-reassoc? (Sig-contracts decl)))
  (define md-entries (loop-md-entries (Sig-contracts decl)))
  (define (line! s) (fprintf o "  ~a\n" s))
  (define (label! l) (fprintf o "~a:\n" l))

  (define (arith ty op)
    (define instr
      (match (list ty op)
        ['(float +) "fadd"] ['(float -) "fsub"] ['(float *) "fmul"] ['(float /) "fdiv"]
        ['(usize +) "add"] ['(usize -) "sub"] ['(usize *) "mul"] ['(usize /) "udiv"]))
    (string-append instr (if (and (eq? ty 'float) reassoc?) " reassoc" "")))

  (define (gep b ix)
    (define elem (Ptr-pointee (hash-ref params b)))
    (define-values (iv _) (ev ix))
    (define r (t!))
    (line! (format "~a = getelementptr inbounds ~a, ptr %~a, i64 ~a" r (llty elem) b iv))
    (values r elem))

  (define (ev e)
    (match e
      [(EInt v) (values (number->string v) 'usize)]
      [(EFloat v) (values (flit v) 'float)]
      [(EVar n)
       (cond
         [(hash-ref params n #f)
          => (λ (ty) (values (format "%~a" n) ty))]
         [else
          (define ty (hash-ref locals n))
          (define r (t!))
          (line! (format "~a = load ~a, ptr %~a.addr" r (llty ty) n))
          (values r ty)])]
      [(EMin a b)
       (define-values (av _ta) (ev a))
       (define-values (bv _tb) (ev b))
       (define c (t!))
       (line! (format "~a = icmp ult i64 ~a, ~a" c av bv))
       (define r (t!))
       (line! (format "~a = select i1 ~a, i64 ~a, i64 ~a" r c av bv))
       (values r 'usize)]
      [(EIndex b ix)
       (define-values (ptr elem) (gep b ix))
       (define r (t!))
       (line! (format "~a = load ~a, ptr ~a" r (llty elem) ptr))
       (values r elem)]
      [(EBin op l r0)
       (define-values (lv lt) (ev l))
       (define-values (rv _) (ev r0))
       (define r (t!))
       (cond
         [(cmp-op? op)
          (define pred
            (match (list lt op)
              ['(usize <) "icmp ult"] ['(usize <=) "icmp ule"]
              ['(usize >) "icmp ugt"] ['(usize >=) "icmp uge"]
              ['(usize ==) "icmp eq"] ['(usize !=) "icmp ne"]
              ['(float <) "fcmp olt"] ['(float <=) "fcmp ole"]
              ['(float >) "fcmp ogt"] ['(float >=) "fcmp oge"]
              ['(float ==) "fcmp oeq"] ['(float !=) "fcmp une"]))
          (line! (format "~a = ~a ~a ~a, ~a" r pred (llty lt) lv rv))
          (values r 'bool)]
         [else
          (line! (format "~a = ~a ~a ~a, ~a" r (arith lt op) (llty lt) lv rv))
          (values r lt)])]))

  (define (st s)
    (match s
      [(SLocal ty name init _)
       (define-values (v _t) (ev init))
       (line! (format "store ~a ~a, ptr %~a.addr" (llty ty) v name))]
      [(SAssign (LvVar n) op value _)
       (define ty (hash-ref locals n))
       (define-values (v _t) (ev value))
       (define fin
         (if (eq? op 'add)
             (let ([old (t!)])
               (line! (format "~a = load ~a, ptr %~a.addr" old (llty ty) n))
               (let ([r (t!)])
                 (line! (format "~a = ~a ~a ~a, ~a" r (arith ty '+) (llty ty) old v))
                 r))
             v))
       (line! (format "store ~a ~a, ptr %~a.addr" (llty ty) fin n))]
      [(SAssign (LvIndex b ix) op value _)
       (define-values (v _t) (ev value))
       (define-values (ptr elem) (gep b ix))
       (define fin
         (if (eq? op 'add)
             (let ([old (t!)])
               (line! (format "~a = load ~a, ptr ~a" old (llty elem) ptr))
               (let ([r (t!)])
                 (line! (format "~a = ~a ~a ~a, ~a" r (arith elem '+) (llty elem) old v))
                 r))
             v))
       (line! (format "store ~a ~a, ptr ~a" (llty elem) fin ptr))]
      [(SFor var init cond-e body _)
       (define n loopn)
       (set! loopn (add1 loopn))
       (define-values (iv _t) (ev init))
       (line! (format "store i64 ~a, ptr %~a.addr" iv var))
       (line! (format "br label %for~a.cond" n))
       (label! (format "for~a.cond" n))
       (define-values (cv _t2) (ev cond-e))
       (line! (format "br i1 ~a, label %for~a.body, label %for~a.end" cv n n))
       (label! (format "for~a.body" n))
       (for ([s2 (in-list body)]) (st s2))
       (line! (format "br label %for~a.inc" n))
       (label! (format "for~a.inc" n))
       (define old (t!))
       (line! (format "~a = load i64, ptr %~a.addr" old var))
       (define inc (t!))
       (line! (format "~a = add nuw i64 ~a, 1" inc old))
       (line! (format "store i64 ~a, ptr %~a.addr" inc var))
       (define md-ref
         (if (null? md-entries)
             ""
             (format ", !llvm.loop !~a" (md-alloc! md-entries))))
       (line! (format "br label %for~a.cond~a" n md-ref))
       (label! (format "for~a.end" n))]
      [(SForStep var bound step sbody _)
       ;; tile loop: 0 .. bound, stride `step`; never carries vectorize
       ;; metadata — it exists to shape locality, not lanes
       (define n loopn)
       (set! loopn (add1 loopn))
       (line! (format "store i64 0, ptr %~a.addr" var))
       (line! (format "br label %for~a.cond" n))
       (label! (format "for~a.cond" n))
       (define iv (t!))
       (line! (format "~a = load i64, ptr %~a.addr" iv var))
       (define-values (bv _tb) (ev bound))
       (define cmp (t!))
       (line! (format "~a = icmp ult i64 ~a, ~a" cmp iv bv))
       (line! (format "br i1 ~a, label %for~a.body, label %for~a.end" cmp n n))
       (label! (format "for~a.body" n))
       (for ([s2 (in-list sbody)]) (st s2))
       (line! (format "br label %for~a.inc" n))
       (label! (format "for~a.inc" n))
       (define old (t!))
       (line! (format "~a = load i64, ptr %~a.addr" old var))
       (define inc (t!))
       (line! (format "~a = add nuw i64 ~a, ~a" inc old step))
       (line! (format "store i64 ~a, ptr %~a.addr" inc var))
       (line! (format "br label %for~a.cond" n))
       (label! (format "for~a.end" n))]
      [(SReturn value _)
       (if value
           (let-values ([(v ty) (ev value)])
             (line! (format "ret ~a ~a" (llty ty) v)))
           (line! "ret void"))]))

  ;; allocas, collected up front
  (define allocs '())
  (define (collect! stmts)
    (for ([s (in-list stmts)])
      (match s
        [(SLocal ty name _ _) (set! allocs (append allocs (list (cons name ty))))]
        [(SFor var _ _ fbody _)
         (set! allocs (append allocs (list (cons var 'usize))))
         (collect! fbody)]
        [(SForStep var _ _ fbody _)
         (set! allocs (append allocs (list (cons var 'usize))))
         (collect! fbody)]
        [_ (void)])))
  (collect! body)

  (label! "entry")
  (for ([a (in-list allocs)])
    (hash-set! locals (car a) (cdr a))
    (line! (format "%~a.addr = alloca ~a, align ~a"
                   (car a) (llty (cdr a)) (if (eq? (cdr a) 'usize) 8 4))))
  (for ([s (in-list body)]) (st s))
  (when (and (eq? (Sig-ret decl) 'void)
             (not (and (pair? body) (SReturn? (car (reverse body))))))
    (line! "ret void"))
  (fprintf o "}\n"))
