#lang racket/base
;; Textual LLVM IR emission. Contracts arrive verified; this is transcription:
;;   @noalias -> noalias, @effect -> readonly/writeonly, @vectorize -> !llvm.loop,
;;   @fp(...) -> fast-math flags on float arithmetic,
;;   @tile / @interchange -> AST transforms (transform.rkt) before emission,
;;   @parallel -> wrapper + worker + alwaysinline body over dispatch_apply_f.
;; Locals are alloca slots; LLVM's mem2reg rebuilds SSA. No datalayout or
;; triple is emitted — the host toolchain supplies its defaults.
(require racket/match racket/string racket/format racket/flonum racket/list
         "ast.rkt" "sema.rkt" "transform.rkt")
(provide emit-module)

(define (llty t)
  (match t
    ['void "void"] ['float "float"] ['usize "i64"] ['bool "i1"]
    [(Ptr _ _) "ptr"]))

;; LLVM spells `float` constants as the bit pattern of the f64 that the f32
;; value widens to.
(define (flit x)
  (define s (flsingle (exact->inexact x)))
  (define bs (real->floating-point-bytes s 8 #t))
  (define n (integer-bytes->integer bs #f #t))
  (format "0x~a" (string-upcase (~r n #:base 16 #:min-width 16 #:pad-string "0"))))

;; the loop metadata a kernel's contracts ask for, as rendered node bodies
(define (loop-md-entries c)
  (define v (Contracts-vectorize c))
  (define u (Contracts-unroll c))
  (append
   (cond
     [(and v (Vectorize-disable? v))
      (list "!{!\"llvm.loop.vectorize.enable\", i1 false}")]
     [v
      (append
       (list "!{!\"llvm.loop.vectorize.enable\", i1 true}")
       (let ([w (Vectorize-width v)])
         (if w (list (format "!{!\"llvm.loop.vectorize.width\", i32 ~a}" w)) '()))
       (let ([il (Vectorize-interleave v)])
         (if il (list (format "!{!\"llvm.loop.interleave.count\", i32 ~a}" il)) '()))
       (if (Vectorize-predicate? v)
           (list "!{!\"llvm.loop.vectorize.predicate.enable\", i1 true}")
           '())
       (if (Vectorize-scalable? v)
           (list "!{!\"llvm.loop.vectorize.scalable.enable\", i1 true}")
           '()))]
     [else '()])
   (if u
       (list (format "!{!\"llvm.loop.unroll.count\", i32 ~a}" (Unroll-count u)))
       '())))

(define (emit-module source-name kernels)
  (define any-stream?
    (ormap (λ (k) (and (Contracts-stream? (Sig-contracts (kernel-decl k))) #t)) kernels))
  ;; reserve !0 for the shared nontemporal node when any kernel streams
  (define nt-id (and any-stream? 0))
  (define md '())     ; list of (id . entries)
  (define md-next (if any-stream? 1 0))
  (define (md-alloc! entries)
    (define id md-next)
    (set! md-next (+ md-next 1 (length entries)))
    (set! md (append md (list (cons id entries))))
    id)
  (define any-parallel?
    (ormap (λ (k) (and (Contracts-parallel (Sig-contracts (kernel-decl k))) #t)) kernels))
  (define o (open-output-string))
  (fprintf o "; generated by wyvec 0.1 (Wyve stage 0, Racket)\nsource_filename = \"~a\"\n" source-name)
  (for ([k (in-list kernels)])
    (fprintf o "\n")
    (emit-kernel o k md-alloc! nt-id))
  (when any-parallel?
    (fprintf o "\ndeclare void @dispatch_apply_f(i64, ptr, ptr, ptr)\n"))
  (fprintf o "\nattributes #0 = { nounwind }\n")
  (when any-parallel?
    (fprintf o "attributes #1 = { nounwind alwaysinline }\n"))
  (when (or any-stream? (not (null? md)))
    (fprintf o "\n")
    (when any-stream?
      (fprintf o "!0 = !{i32 1}\n"))
    (for ([entry (in-list md)])
      (define id (car entry))
      (define bodies (cdr entry))
      (fprintf o "!~a = distinct !{~a}\n" id
               (string-join (for/list ([i (in-range (add1 (length bodies)))])
                              (format "!~a" (+ id i)))
                            ", "))
      (for ([b (in-list bodies)] [i (in-naturals 1)])
        (fprintf o "!~a = ~a\n" (+ id i) b))))
  (get-output-string o))

(define (emit-kernel o k md-alloc! nt-id)
  (define decl (kernel-decl k))
  (define cs (Sig-contracts decl))
  (define eff (Contracts-effect cs))
  (define fp-str
    (apply string-append
           (for/list ([f (in-list (Contracts-fp-flags cs))]) (format " ~a" f))))
  (define md-entries (loop-md-entries cs))
  (define params-hash
    (for/hash ([p (in-list (sig-params decl))]) (values (Param-name p) (Param-ty p))))
  (define params-by-name
    (for/hash ([p (in-list (sig-params decl))]) (values (Param-name p) p)))
  ;; the alignment to use for a vector load/store of `base` (param align, or
  ;; element align)
  (define (varr-align base)
    (or (Param-align (hash-ref params-by-name base)) 4))
  ;; arrays written but not read — their stores may be nontemporal
  (define write-only
    (if (and (Contracts-stream? cs) eff)
        (for/hash ([w (in-list (Effect-writes eff))]
                   #:unless (member w (Effect-reads eff)))
          (values w #t))
        (hash)))
  ;; suffix appended to a store into a write-only array under @stream
  (define (nt-suffix base)
    (if (and nt-id (hash-ref write-only base #f))
        (format ", !nontemporal !~a" nt-id)
        ""))

  ;; scheduling transforms run here, above LLVM, on the proven AST
  (define body
    (let* ([b (MethodDef-body (kernel-def k))]
           [b (let ([ti (Contracts-tile cs)])
                (if ti (apply-tile b (Tile-pairs ti)) b))]
           [b (let ([ic (Contracts-interchange cs)])
                (if ic (apply-interchange b (Interchange-outer ic) (Interchange-inner ic)) b))])
      b))

  (define (param-decl p)
    (define attrs
      (if (Ptr? (Param-ty p))
          (let* ([r (if eff
                        (and (member (Param-name p) (Effect-reads eff)) #t)
                        (Ptr-const? (Param-ty p)))]
                 [w (if eff
                        (and (member (Param-name p) (Effect-writes eff)) #t)
                        #f)])
            (string-append
             (if (Param-noalias? p) " noalias" "")
             " nocapture"
             (cond [(and r (not w)) " readonly"]
                   [(and w (not r)) " writeonly"]
                   [else ""])
             (if (Param-align p) (format " align ~a" (Param-align p)) "")))
          ""))
    (format "~a~a %~a" (llty (Param-ty p)) attrs (Param-name p)))

  ;; ---- one function's worth of emission machinery ----
  (define (emit-fn #:name name
                   #:stmts stmts
                   #:linkage [linkage ""]
                   #:attrs [attrs "#0"]
                   #:extra-args [extra ""]
                   #:extra-allocas [xall '()]
                   #:prologue [prologue '()]
                   #:ret [ret (Sig-ret decl)])
    (define tmp 0)
    (define loopn 0)
    (define (t!) (begin0 (format "%t~a" tmp) (set! tmp (add1 tmp))))
    (define locals (make-hash))
    (define (line! s) (fprintf o "  ~a\n" s))
    (define (label! l) (fprintf o "~a:\n" l))

    (define (arith ty op)
      (define instr
        (match (list ty op)
          ['(float +) "fadd"] ['(float -) "fsub"] ['(float *) "fmul"] ['(float /) "fdiv"]
          ['(usize +) "add"] ['(usize -) "sub"] ['(usize *) "mul"] ['(usize /) "udiv"]))
      (string-append instr (if (eq? ty 'float) fp-str "")))

    (define (gep b ix)
      (define elem (Ptr-pointee (hash-ref params-hash b)))
      (define-values (iv _) (ev ix))
      (define r (t!))
      (line! (format "~a = getelementptr inbounds ~a, ptr %~a, i64 ~a" r (llty elem) b iv))
      (values r elem))

    (define (ev e)
      (match e
        [(EInt v) (values (number->string v) 'usize)]
        [(EFloat v) (values (flit v) 'float)]
        [(EVar n)
         (cond
           [(hash-ref params-hash n #f)
            => (λ (ty) (values (format "%~a" n) ty))]
           [else
            (define ty (hash-ref locals n))
            (define r (t!))
            (line! (format "~a = load ~a, ptr %~a.addr" r (llty ty) n))
            (values r ty)])]
        [(EMin a b)
         (define-values (av _ta) (ev a))
         (define-values (bv _tb) (ev b))
         (define c (t!))
         (line! (format "~a = icmp ult i64 ~a, ~a" c av bv))
         (define r (t!))
         (line! (format "~a = select i1 ~a, i64 ~a, i64 ~a" r c av bv))
         (values r 'usize)]
        [(EIndex b ix)
         (define-values (ptr elem) (gep b ix))
         (define r (t!))
         (line! (format "~a = load ~a, ptr ~a" r (llty elem) ptr))
         (values r elem)]
        [(EBin op l r0)
         (define-values (lv lt) (ev l))
         (define-values (rv _) (ev r0))
         (define r (t!))
         (cond
           [(cmp-op? op)
            (define pred
              (match (list lt op)
                ['(usize <) "icmp ult"] ['(usize <=) "icmp ule"]
                ['(usize >) "icmp ugt"] ['(usize >=) "icmp uge"]
                ['(usize ==) "icmp eq"] ['(usize !=) "icmp ne"]
                ['(float <) "fcmp olt"] ['(float <=) "fcmp ole"]
                ['(float >) "fcmp ogt"] ['(float >=) "fcmp oge"]
                ['(float ==) "fcmp oeq"] ['(float !=) "fcmp une"]))
            (line! (format "~a = ~a ~a ~a, ~a" r pred (llty lt) lv rv))
            (values r 'bool)]
           [else
            (line! (format "~a = ~a ~a ~a, ~a" r (arith lt op) (llty lt) lv rv))
            (values r lt)])]))

    (define (st s)
      (match s
        [(SLocal ty name init _)
         (define-values (v _t) (ev init))
         (line! (format "store ~a ~a, ptr %~a.addr" (llty ty) v name))]
        [(SAssign (LvVar n) op value _)
         (define ty (hash-ref locals n))
         (define-values (v _t) (ev value))
         (define fin
           (if (eq? op 'add)
               (let ([old (t!)])
                 (line! (format "~a = load ~a, ptr %~a.addr" old (llty ty) n))
                 (let ([r (t!)])
                   (line! (format "~a = ~a ~a ~a, ~a" r (arith ty '+) (llty ty) old v))
                   r))
               v))
         (line! (format "store ~a ~a, ptr %~a.addr" (llty ty) fin n))]
        [(SAssign (LvIndex b ix) op value _)
         (define-values (v _t) (ev value))
         (define-values (ptr elem) (gep b ix))
         (define fin
           (if (eq? op 'add)
               (let ([old (t!)])
                 (line! (format "~a = load ~a, ptr ~a" old (llty elem) ptr))
                 (let ([r (t!)])
                   (line! (format "~a = ~a ~a ~a, ~a" r (arith elem '+) (llty elem) old v))
                   r))
               v))
         (line! (format "store ~a ~a, ptr ~a~a" (llty elem) fin ptr (nt-suffix b)))]
        [(SFor var init cond-e fbody _)
         (define n loopn)
         (set! loopn (add1 loopn))
         (define-values (iv _t) (ev init))
         (line! (format "store i64 ~a, ptr %~a.addr" iv var))
         (line! (format "br label %for~a.cond" n))
         (label! (format "for~a.cond" n))
         (define-values (cv _t2) (ev cond-e))
         (line! (format "br i1 ~a, label %for~a.body, label %for~a.end" cv n n))
         (label! (format "for~a.body" n))
         (for ([s2 (in-list fbody)]) (st s2))
         (line! (format "br label %for~a.inc" n))
         (label! (format "for~a.inc" n))
         (define old (t!))
         (line! (format "~a = load i64, ptr %~a.addr" old var))
         (define inc (t!))
         (line! (format "~a = add nuw i64 ~a, 1" inc old))
         (line! (format "store i64 ~a, ptr %~a.addr" inc var))
         (define md-ref
           (if (null? md-entries)
               ""
               (format ", !llvm.loop !~a" (md-alloc! md-entries))))
         (line! (format "br label %for~a.cond~a" n md-ref))
         (label! (format "for~a.end" n))]
        [(SForStep var bound step sbody _)
         ;; tile loop: 0 .. bound, stride `step`; never carries vectorize
         ;; metadata — it exists to shape locality, not lanes
         (define n loopn)
         (set! loopn (add1 loopn))
         (line! (format "store i64 0, ptr %~a.addr" var))
         (line! (format "br label %for~a.cond" n))
         (label! (format "for~a.cond" n))
         (define iv (t!))
         (line! (format "~a = load i64, ptr %~a.addr" iv var))
         (define-values (bv _tb) (ev bound))
         (define cmp (t!))
         (line! (format "~a = icmp ult i64 ~a, ~a" cmp iv bv))
         (line! (format "br i1 ~a, label %for~a.body, label %for~a.end" cmp n n))
         (label! (format "for~a.body" n))
         (for ([s2 (in-list sbody)]) (st s2))
         (line! (format "br label %for~a.inc" n))
         (label! (format "for~a.inc" n))
         (define old (t!))
         (line! (format "~a = load i64, ptr %~a.addr" old var))
         (define inc (t!))
         (line! (format "~a = add nuw i64 ~a, ~a" inc old step))
         (line! (format "store i64 ~a, ptr %~a.addr" inc var))
         (line! (format "br label %for~a.cond" n))
         (label! (format "for~a.end" n))]
        [(SReturn value _)
         (if value
             (let-values ([(v ty) (ev value)])
               (line! (format "ret ~a ~a" (llty ty) v)))
             (line! "ret void"))]))

    ;; header
    (fprintf o "define ~a~a @~a(~a~a) ~a {\n"
             linkage (llty ret) name
             (string-join (map param-decl (sig-params decl)) ", ")
             extra attrs)
    (label! "entry")
    ;; allocas (deduped — transforms may reuse loop vars in sibling loops)
    (define allocs '())
    (define seen-allocs (make-hash))
    (define (alloca! nm ty)
      (unless (hash-ref seen-allocs nm #f)
        (hash-set! seen-allocs nm #t)
        (set! allocs (append allocs (list (cons nm ty))))))
    (for ([a (in-list xall)]) (alloca! (car a) (cdr a)))
    (define (collect! stmts*)
      (for ([s (in-list stmts*)])
        (match s
          [(SLocal ty nm _ _) (alloca! nm ty)]
          [(SFor var _ _ fb _) (alloca! var 'usize) (collect! fb)]
          [(SForStep var _ _ fb _) (alloca! var 'usize) (collect! fb)]
          [_ (void)])))
    (collect! stmts)
    (for ([a (in-list allocs)])
      (hash-set! locals (car a) (cdr a))
      (line! (format "%~a.addr = alloca ~a, align ~a"
                     (car a) (llty (cdr a)) (if (eq? (cdr a) 'usize) 8 4))))
    (for ([pl (in-list prologue)]) (line! pl))
    (for ([s (in-list stmts)]) (st s))
    (when (and (eq? ret 'void)
               (not (and (pair? stmts) (SReturn? (car (reverse stmts))))))
      (line! "ret void"))
    (fprintf o "}\n"))

  ;; @vectorize(manual): wyvec vectorizes the elementwise loop itself — a
  ;; vector main loop (so @stream's nontemporal can ride a vector store, and
  ;; @align gives aligned vector ops) plus a scalar remainder.
  (define (emit-manual)
    (define vz (Contracts-vectorize cs))
    (define W (Vectorize-width vz))
    (define vty (format "<~a x float>" W))
    (match-define (list (SFor _iv (EInt 0) (EBin '< _ bound-e) lbody _)) body)
    (define bound (match bound-e [(EVar n) (format "%~a" n)] [(EInt c) (number->string c)]))
    (fprintf o "; kernel ~a [~a] — @vectorize(manual, width: ~a)\n"
             (kernel-iface k) (sig-selector decl) W)
    (fprintf o "define void @~a(~a) #0 {\n" (kernel-symbol k)
             (string-join (map param-decl (sig-params decl)) ", "))
    (define tmp 0)
    (define (t!) (begin0 (format "%t~a" tmp) (set! tmp (add1 tmp))))
    (define (line! s) (fprintf o "  ~a\n" s))
    (define (label! l) (fprintf o "~a:\n" l))
    (define (gep base idx)
      (define r (t!))
      (line! (format "~a = getelementptr inbounds float, ptr %~a, i64 ~a" r base idx))
      r)
    ;; float arithmetic instruction + the kernel's fp flags (same for scalar
    ;; and vector — only the operand type differs)
    (define (fop op)
      (string-append (match op ['+ "fadd"] ['- "fsub"] ['* "fmul"] ['/ "fdiv"]) fp-str))
    ;; --- vector evaluator: returns an operand of type `vty` ---
    (define (vsplat scalar)
      (define a (t!))
      (line! (format "~a = insertelement ~a poison, float ~a, i64 0" a vty scalar))
      (define b (t!))
      (line! (format "~a = shufflevector ~a ~a, ~a poison, <~a x i32> zeroinitializer" b vty a vty W))
      b)
    (define (vev e idx)
      (match e
        [(EFloat c) (format "<~a>" (string-join (make-list W (format "float ~a" (flit c))) ", "))]
        [(EVar n) (vsplat (format "%~a" n))]      ; scalar float param
        [(EIndex base (EVar _)) ; offset 0, guaranteed by sema
         (define p (gep base idx))
         (define r (t!))
         (line! (format "~a = load ~a, ptr ~a, align ~a" r vty p (varr-align base)))
         r]
        [(EBin op l r0)
         (define lv (vev l idx))
         (define rv (vev r0 idx))
         (define res (t!))
         (line! (format "~a = ~a ~a ~a, ~a" res (fop op) vty lv rv))
         res]))
    ;; --- scalar evaluator for the remainder ---
    (define (sev e idx)
      (match e
        [(EFloat c) (flit c)]
        [(EVar n) (format "%~a" n)]
        [(EIndex base (EVar _))
         (define p (gep base idx))
         (define r (t!))
         (line! (format "~a = load float, ptr ~a" r p))
         r]
        [(EBin op l r0)
         (define lv (sev l idx))
         (define rv (sev r0 idx))
         (define res (t!))
         (line! (format "~a = ~a float ~a, ~a" res (fop op) lv rv))
         res]))
    (label! "entry")
    (line! "%i.addr = alloca i64, align 8")
    (line! "store i64 0, ptr %i.addr")
    (line! (format "%vn = and i64 ~a, ~a" bound (- W)))   ; bound rounded down to a multiple of W
    (line! "br label %vec.cond")
    (label! "vec.cond")
    (define vi (t!))
    (line! (format "~a = load i64, ptr %i.addr" vi))
    (define vc (t!))
    (line! (format "~a = icmp ult i64 ~a, %vn" vc vi))
    (line! (format "br i1 ~a, label %vec.body, label %tail.cond" vc))
    (label! "vec.body")
    (define vidx (t!))
    (line! (format "~a = load i64, ptr %i.addr" vidx))
    (for ([s (in-list lbody)])
      (match-define (SAssign (LvIndex base (EVar _)) 'set value _) s)
      (define val (vev value vidx))
      (define dp (gep base vidx))
      (line! (format "store ~a ~a, ptr ~a, align ~a~a" vty val dp (varr-align base) (nt-suffix base))))
    (define vinc (t!))
    (line! (format "~a = add nuw i64 ~a, ~a" vinc vidx W))
    (line! (format "store i64 ~a, ptr %i.addr" vinc))
    (line! "br label %vec.cond")
    (label! "tail.cond")
    (define ti (t!))
    (line! (format "~a = load i64, ptr %i.addr" ti))
    (define tc (t!))
    (line! (format "~a = icmp ult i64 ~a, ~a" tc ti bound))
    (line! (format "br i1 ~a, label %tail.body, label %done" tc))
    (label! "tail.body")
    (define tidx (t!))
    (line! (format "~a = load i64, ptr %i.addr" tidx))
    (for ([s (in-list lbody)])
      (match-define (SAssign (LvIndex base (EVar _)) 'set value _) s)
      (define val (sev value tidx))
      (define dp (gep base tidx))
      (line! (format "store float ~a, ptr ~a~a" val dp (nt-suffix base))))
    (define tinc (t!))
    (line! (format "~a = add nuw i64 ~a, 1" tinc tidx))
    (line! (format "store i64 ~a, ptr %i.addr" tinc))
    (line! "br label %tail.cond")
    (label! "done")
    (line! "ret void")
    (fprintf o "}\n"))

  ;; ---- kernel layouts ----
  (define par (Contracts-parallel cs))
  (cond
    [(and (Contracts-vectorize cs) (Vectorize-manual? (Contracts-vectorize cs)))
     (emit-manual)]
    [(not par)
     (fprintf o "; kernel ~a [~a]\n" (kernel-iface k) (sig-selector decl))
     (emit-fn #:name (kernel-symbol k) #:stmts body)]
    [else
     ;; @parallel(i): wrapper packs args and dispatches; worker unpacks and
     ;; calls an alwaysinline body fn that keeps the original parameter
     ;; attributes — inlining turns noalias params into scoped metadata,
     ;; so the inner loops stay vectorizable.
     (match-define (list (SFor piv _ pcond plbody _)) body)
     (define bound-v
       (match pcond
         [(EBin '< _ (EVar v)) (format "%~a" v)]
         [(EBin '< _ (EInt c)) (number->string c)]))
     (define sym (kernel-symbol k))
     (define ps (sig-params decl))
     (define ctx-ty (format "%~a.ctx" sym))
     (fprintf o "; kernel ~a [~a] — @parallel(~a) over dispatch_apply_f\n"
              (kernel-iface k) (sig-selector decl) piv)
     (fprintf o "~a = type { ~a }\n"
              ctx-ty (string-join (for/list ([p ps]) (llty (Param-ty p))) ", "))
     ;; wrapper (public ABI unchanged)
     (fprintf o "define void @~a(~a) #0 {\nentry:\n  %ctx = alloca ~a, align 8\n"
              sym (string-join (map param-decl ps) ", ") ctx-ty)
     (for ([p ps] [i (in-naturals)])
       (fprintf o "  %f~a = getelementptr inbounds ~a, ptr %ctx, i32 0, i32 ~a\n" i ctx-ty i)
       (fprintf o "  store ~a %~a, ptr %f~a\n" (llty (Param-ty p)) (Param-name p) i))
     (fprintf o "  call void @dispatch_apply_f(i64 ~a, ptr null, ptr %ctx, ptr @~a.worker)\n"
              bound-v sym)
     (fprintf o "  ret void\n}\n")
     ;; worker (libdispatch shape): unpack, call body
     (fprintf o "define internal void @~a.worker(ptr %ctx, i64 %chunk) #0 {\nentry:\n" sym)
     (for ([p ps] [i (in-naturals)])
       (fprintf o "  %f~a = getelementptr inbounds ~a, ptr %ctx, i32 0, i32 ~a\n" i ctx-ty i)
       (fprintf o "  %~a = load ~a, ptr %f~a\n" (Param-name p) (llty (Param-ty p)) i))
     (fprintf o "  call void @~a.body(~a, i64 %chunk)\n"
              sym
              (string-join (for/list ([p ps])
                             (format "~a %~a" (llty (Param-ty p)) (Param-name p)))
                           ", "))
     (fprintf o "  ret void\n}\n")
     ;; body: one iteration of the outer loop, original attrs, alwaysinline
     (emit-fn #:name (format "~a.body" sym)
              #:stmts plbody
              #:linkage "internal "
              #:attrs "#1"
              #:extra-args ", i64 %chunk"
              #:extra-allocas (list (cons piv 'usize))
              #:prologue (list (format "store i64 %chunk, ptr %~a.addr" piv))
              #:ret 'void)]))
