//! Textual LLVM IR emission. Contracts arrive here already verified by sema;
//! this module's job is pure transcription:
//!
//!   @noalias            -> `noalias` parameter attribute
//!   @effect(reads/...)  -> per-parameter `readonly` / `writeonly`
//!   @vectorize          -> `!llvm.loop` vectorize.enable / vectorize.width
//!   @fp(reassoc)        -> `reassoc` flag on float arithmetic
//!
//! Locals are alloca slots; LLVM's mem2reg rebuilds SSA. No datalayout or
//! triple is emitted — the host toolchain supplies its defaults.

use crate::ast::*;
use crate::sema::Kernel;
use std::collections::HashMap;

pub fn emit(source_name: &str, kernels: &[Kernel]) -> String {
    let mut md = MdTable::default();
    let mut out = String::new();
    out.push_str(&format!(
        "; generated by wyvec 0.0.1 (Wyve stage 0)\nsource_filename = \"{}\"\n",
        source_name
    ));
    for k in kernels {
        out.push('\n');
        emit_kernel(&mut out, k, &mut md);
    }
    out.push_str("\nattributes #0 = { nounwind }\n");
    if !md.loops.is_empty() {
        out.push('\n');
        out.push_str(&md.render());
    }
    out
}

#[derive(Default)]
struct MdTable {
    loops: Vec<(u32, Option<u32>)>, // (first metadata id, vectorize width)
    next: u32,
}

impl MdTable {
    fn alloc(&mut self, width: Option<u32>) -> u32 {
        let id = self.next;
        self.next += if width.is_some() { 3 } else { 2 };
        self.loops.push((id, width));
        id
    }

    fn render(&self) -> String {
        let mut s = String::new();
        for (id, width) in &self.loops {
            match width {
                Some(w) => {
                    s.push_str(&format!("!{} = distinct !{{!{}, !{}, !{}}}\n", id, id, id + 1, id + 2));
                    s.push_str(&format!("!{} = !{{!\"llvm.loop.vectorize.enable\", i1 true}}\n", id + 1));
                    s.push_str(&format!("!{} = !{{!\"llvm.loop.vectorize.width\", i32 {}}}\n", id + 2, w));
                }
                None => {
                    s.push_str(&format!("!{} = distinct !{{!{}, !{}}}\n", id, id, id + 1));
                    s.push_str(&format!("!{} = !{{!\"llvm.loop.vectorize.enable\", i1 true}}\n", id + 1));
                }
            }
        }
        s
    }
}

fn llty(t: &Type) -> &'static str {
    match t {
        Type::Void => "void",
        Type::Float => "float",
        Type::Usize => "i64",
        Type::Bool => "i1",
        Type::Ptr { .. } => "ptr",
    }
}

/// LLVM spells `float` constants as the bit pattern of the f64 that the f32
/// value widens to (decimal text is only accepted when exactly representable).
fn flit(f: f32) -> String {
    format!("0x{:016X}", (f as f64).to_bits())
}

fn emit_kernel(out: &mut String, k: &Kernel, md: &mut MdTable) {
    let sig = k.decl;
    let eff = &sig.contracts.effect;

    let mut ps = Vec::new();
    for p in sig.params() {
        let mut s = llty(&p.ty).to_string();
        if let Type::Ptr { is_const, .. } = &p.ty {
            if p.noalias {
                s.push_str(" noalias");
            }
            s.push_str(" nocapture");
            let (r, w) = match eff {
                Some(e) => (e.reads.contains(&p.name), e.writes.contains(&p.name)),
                None => (*is_const, false),
            };
            if r && !w {
                s.push_str(" readonly");
            } else if w && !r {
                s.push_str(" writeonly");
            }
        }
        s.push_str(&format!(" %{}", p.name));
        ps.push(s);
    }
    out.push_str(&format!(
        "; kernel {} [{}]\ndefine {} @{}({}) #0 {{\n",
        k.iface,
        sig.selector(),
        llty(&sig.ret),
        k.symbol,
        ps.join(", ")
    ));

    let mut em = Emitter {
        buf: String::new(),
        tmp: 0,
        loopn: 0,
        locals: HashMap::new(),
        params: sig.params().map(|p| (p.name.clone(), p.ty.clone())).collect(),
        reassoc: sig.contracts.fp_reassoc,
        vmd: sig.contracts.vectorize.as_ref(),
        md,
    };

    let mut allocs = Vec::new();
    collect_allocas(&k.def.body, &mut allocs);
    em.label("entry");
    for (name, ty) in &allocs {
        em.locals.insert(name.clone(), ty.clone());
        let align = match ty {
            Type::Usize => 8,
            Type::Float => 4,
            _ => unreachable!("only scalar locals exist in stage 0"),
        };
        em.line(format!("%{}.addr = alloca {}, align {}", name, llty(ty), align));
    }
    for s in &k.def.body {
        em.stmt(s);
    }
    if sig.ret == Type::Void && !matches!(k.def.body.last(), Some(Stmt::Return { .. })) {
        em.line("ret void");
    }

    out.push_str(&em.buf);
    out.push_str("}\n");
}

fn collect_allocas(stmts: &[Stmt], out: &mut Vec<(String, Type)>) {
    for s in stmts {
        match s {
            Stmt::Local { name, ty, .. } => out.push((name.clone(), ty.clone())),
            Stmt::For { var, body, .. } => {
                out.push((var.clone(), Type::Usize));
                collect_allocas(body, out);
            }
            _ => {}
        }
    }
}

struct Emitter<'a> {
    buf: String,
    tmp: u32,
    loopn: u32,
    locals: HashMap<String, Type>,
    params: HashMap<String, Type>,
    reassoc: bool,
    vmd: Option<&'a Vectorize>,
    md: &'a mut MdTable,
}

impl Emitter<'_> {
    fn line(&mut self, s: impl AsRef<str>) {
        self.buf.push_str("  ");
        self.buf.push_str(s.as_ref());
        self.buf.push('\n');
    }

    fn label(&mut self, l: &str) {
        self.buf.push_str(l);
        self.buf.push_str(":\n");
    }

    fn t(&mut self) -> String {
        let n = self.tmp;
        self.tmp += 1;
        format!("%t{}", n)
    }

    fn eval(&mut self, e: &Expr) -> (String, Type) {
        match e {
            Expr::Int(v) => (v.to_string(), Type::Usize),
            Expr::Float(f) => (flit(*f), Type::Float),
            Expr::Var(n) => {
                if let Some(t) = self.params.get(n).cloned() {
                    (format!("%{}", n), t)
                } else {
                    let ty = self.locals[n].clone();
                    let r = self.t();
                    self.line(format!("{} = load {}, ptr %{}.addr", r, llty(&ty), n));
                    (r, ty)
                }
            }
            Expr::Index { base, index } => {
                let (ptr, elem) = self.gep(base, index);
                let r = self.t();
                self.line(format!("{} = load {}, ptr {}", r, llty(&elem), ptr));
                (r, elem)
            }
            Expr::Bin { op, lhs, rhs } => {
                let (lv, lt) = self.eval(lhs);
                let (rv, _) = self.eval(rhs);
                let r = self.t();
                if op.is_cmp() {
                    let pred = match (&lt, op) {
                        (Type::Usize, BinOp::Lt) => "icmp ult",
                        (Type::Usize, BinOp::Le) => "icmp ule",
                        (Type::Usize, BinOp::Gt) => "icmp ugt",
                        (Type::Usize, BinOp::Ge) => "icmp uge",
                        (Type::Usize, BinOp::Eq) => "icmp eq",
                        (Type::Usize, BinOp::Ne) => "icmp ne",
                        (Type::Float, BinOp::Lt) => "fcmp olt",
                        (Type::Float, BinOp::Le) => "fcmp ole",
                        (Type::Float, BinOp::Gt) => "fcmp ogt",
                        (Type::Float, BinOp::Ge) => "fcmp oge",
                        (Type::Float, BinOp::Eq) => "fcmp oeq",
                        (Type::Float, BinOp::Ne) => "fcmp une",
                        _ => unreachable!("sema admits only numeric comparisons"),
                    };
                    self.line(format!("{} = {} {} {}, {}", r, pred, llty(&lt), lv, rv));
                    (r, Type::Bool)
                } else {
                    let (instr, flags) = self.arith(&lt, *op);
                    self.line(format!("{} = {}{} {} {}, {}", r, instr, flags, llty(&lt), lv, rv));
                    (r, lt)
                }
            }
        }
    }

    fn arith(&self, ty: &Type, op: BinOp) -> (&'static str, &'static str) {
        let instr = match (ty, op) {
            (Type::Float, BinOp::Add) => "fadd",
            (Type::Float, BinOp::Sub) => "fsub",
            (Type::Float, BinOp::Mul) => "fmul",
            (Type::Float, BinOp::Div) => "fdiv",
            (Type::Usize, BinOp::Add) => "add",
            (Type::Usize, BinOp::Sub) => "sub",
            (Type::Usize, BinOp::Mul) => "mul",
            (Type::Usize, BinOp::Div) => "udiv",
            _ => unreachable!("sema admits only numeric arithmetic"),
        };
        let flags = if matches!(ty, Type::Float) && self.reassoc { " reassoc" } else { "" };
        (instr, flags)
    }

    fn gep(&mut self, base: &str, index: &Expr) -> (String, Type) {
        let Some(Type::Ptr { pointee, .. }) = self.params.get(base).cloned() else {
            unreachable!("sema guarantees indexed bases are pointer parameters")
        };
        let (iv, _) = self.eval(index);
        let r = self.t();
        self.line(format!("{} = getelementptr inbounds {}, ptr %{}, i64 {}", r, llty(&pointee), base, iv));
        (r, *pointee)
    }

    fn stmt(&mut self, s: &Stmt) {
        match s {
            Stmt::Local { name, ty, init, .. } => {
                let (v, _) = self.eval(init);
                self.line(format!("store {} {}, ptr %{}.addr", llty(ty), v, name));
            }
            Stmt::Assign { target, op, value, .. } => match target {
                LValue::Var(n) => {
                    let ty = self.locals[n].clone();
                    let (v, _) = self.eval(value);
                    let fin = if *op == AssignOp::Add {
                        let old = self.t();
                        self.line(format!("{} = load {}, ptr %{}.addr", old, llty(&ty), n));
                        let r = self.t();
                        let (instr, flags) = self.arith(&ty, BinOp::Add);
                        self.line(format!("{} = {}{} {} {}, {}", r, instr, flags, llty(&ty), old, v));
                        r
                    } else {
                        v
                    };
                    self.line(format!("store {} {}, ptr %{}.addr", llty(&ty), fin, n));
                }
                LValue::Index { base, index } => {
                    let (v, _) = self.eval(value);
                    let (ptr, elem) = self.gep(base, index);
                    let fin = if *op == AssignOp::Add {
                        let old = self.t();
                        self.line(format!("{} = load {}, ptr {}", old, llty(&elem), ptr));
                        let r = self.t();
                        let (instr, flags) = self.arith(&elem, BinOp::Add);
                        self.line(format!("{} = {}{} {} {}, {}", r, instr, flags, llty(&elem), old, v));
                        r
                    } else {
                        v
                    };
                    self.line(format!("store {} {}, ptr {}", llty(&elem), fin, ptr));
                }
            },
            Stmt::For { var, init, cond, body, .. } => {
                let n = self.loopn;
                self.loopn += 1;
                let (iv, _) = self.eval(init);
                self.line(format!("store i64 {}, ptr %{}.addr", iv, var));
                self.line(format!("br label %for{}.cond", n));
                self.label(&format!("for{}.cond", n));
                let (cv, _) = self.eval(cond);
                self.line(format!("br i1 {}, label %for{}.body, label %for{}.end", cv, n, n));
                self.label(&format!("for{}.body", n));
                for st in body {
                    self.stmt(st);
                }
                self.line(format!("br label %for{}.inc", n));
                self.label(&format!("for{}.inc", n));
                let old = self.t();
                self.line(format!("{} = load i64, ptr %{}.addr", old, var));
                let inc = self.t();
                self.line(format!("{} = add nuw i64 {}, 1", inc, old));
                self.line(format!("store i64 {}, ptr %{}.addr", inc, var));
                let md_ref = match self.vmd {
                    Some(v) => {
                        let id = self.md.alloc(v.width);
                        format!(", !llvm.loop !{}", id)
                    }
                    None => String::new(),
                };
                self.line(format!("br label %for{}.cond{}", n, md_ref));
                self.label(&format!("for{}.end", n));
            }
            Stmt::Return { value, .. } => match value {
                Some(e) => {
                    let (v, t) = self.eval(e);
                    self.line(format!("ret {} {}", llty(&t), v));
                }
                None => self.line("ret void"),
            },
        }
    }
}
